; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=AudioFile
AppVersion=1.1
DefaultDirName={pf}\AudioFile
OutputDir=C:\AudioFile_Builds
OutputBaseFilename=AudioFileInstaller
Compression=lzma2
SolidCompression=yes

[Files]
Source: "C:\AudioFile_Builds\AudioFile\*"; DestDir: "{app}"; Flags: recursesubdirs


[Icons]
Name: "{group}\AudioFile"; Filename: "{app}\AudioFile.exe"
